INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('141杂货店','Sān-Z, HOYO-MiX','极限委托','https://www.youtube.com/watch?v=NqfOck2aou4',25,1,26),
	 ('A BRIEF HISTORY OF THE FUTURE','STARSET','DIVISIONS','https://www.youtube.com/watch?v=vKdiqVHRatA',97,20,1723),
	 ('A Lesson Learned','Limp Bizkit','Significant Other','https://www.youtube.com/watch?v=JrerNLcqdXk',159,1,156),
	 ('A Place for My Head','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=Th-VIM6_GSc',184,2,540),
	 ('AD ASTRA','STARSET','SILOS','https://www.youtube.com/watch?v=paiERHE6AfM',276,10,2146),
	 ('Alienation','Three Days Grace','Alienation','https://www.youtube.com/watch?v=xlWfZt13gIg',175,1,4),
	 ('Already Gone','Disturbed','Evolution','https://www.youtube.com/watch?v=qU9lK0pXWas',268,1,85),
	 ('Animal I Have Become','Three Days Grace','One-X','https://www.youtube.com/watch?v=ysho2xTWUYo',231,1,0),
	 ('ANNIHILATED LOVE','STARSET','HORIZONS','https://www.youtube.com/watch?v=wG7D5xITxos',284,1,277),
	 ('Antigravity','STARSET','Transmissions','https://www.youtube.com/watch?v=dFzGX3yBnWE',369,4,1446);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Are You Ready','Disturbed','Evolution','https://www.youtube.com/watch?v=N5U8O81jtAg',261,2,69),
	 ('As the sugar cube floats, fleeting in time (feat. 阿兰','达瓦卓玛), Sān-Z, HOYO-MiX, 阿兰, 达瓦卓玛','As the sugar cube floats, fleeting in time','https://www.youtube.com/watch?v=yk3wBP6ZUb4',209,1,0),
	 ('at his altar','STARSET','SILOS','https://www.youtube.com/watch?v=BewFioz91Mk',100,10,888),
	 ('Avarice','Disturbed','Ten Thousand Fists','https://www.youtube.com/watch?v=VtQWeauQB_0',176,1,0),
	 ('Bad Man','Disturbed','Divisive','https://www.youtube.com/watch?v=kqpVeKwpZSA',202,1,197),
	 ('Believe','Disturbed','Believe','https://www.youtube.com/watch?v=8OyiiPt4AXw',267,4,264),
	 ('Bleed It Out','Linkin Park','Papercuts','https://www.youtube.com/watch?v=bO3kHRIhA0o',164,10,1599),
	 ('BRAVE NEW WORLD','STARSET','SILOS','https://www.youtube.com/watch?v=D3OWHf8ZbII',264,9,2717),
	 ('Break Stuff','Limp Bizkit','Significant Other','https://www.youtube.com/watch?v=41U9Krzg0Aw',166,1,164),
	 ('Breaking the Habit','Linkin Park','Meteora','https://www.youtube.com/watch?v=_e7bqZGPyFI',196,3,433);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Bring It Back','Limp Bizkit','Gold Cobra','https://www.youtube.com/watch?v=y1PfNTiR9BM',137,1,136),
	 ('Bringing It Down','STARSET','Vessels','https://www.youtube.com/watch?v=0oR44c5dMDM',348,4,676),
	 ('Bringing It Down (Version 2.0)','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=qB3w2-ESdek',298,1,289),
	 ('By Myself','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=3vAaLjXKJJw',189,14,2713),
	 ('Carnivore','STARSET','Transmissions','https://www.youtube.com/watch?v=2IHNBjd3nBs',262,3,745),
	 ('Chasing The First Time','Three Days Grace','Outsider','https://www.youtube.com/watch?v=Kt6llBGD4k8',175,1,139),
	 ('Choice','Sān-Z, HOYO-MiX','极限委托','https://www.youtube.com/watch?v=iVcVYeV-9Gg',83,1,0),
	 ('Come Alive','Sān-Z, HOYO-MiX','Come Alive','https://www.youtube.com/watch?v=R3tZmmiKi0o',243,1,236),
	 ('Come Alive Stripped.','Sān-Z, HOYO-MiX, 雷声, Philip Strand','极限委托','https://www.youtube.com/watch?v=iq04zO33pjU',215,1,0),
	 ('Crawling','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=Kb49V5bAERc',209,3,925);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Criminal','Disturbed','Indestructible','https://www.youtube.com/watch?v=KoGxXwIVM04',255,1,1),
	 ('Cure for the Itch','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=WZQz2oxy-V8',157,13,2093),
	 ('Dark On Me','STARSET','Transmissions','https://www.youtube.com/watch?v=XnYURSlYlvc',338,1,329),
	 ('DARK THINGS','STARSET','SILOS','https://www.youtube.com/watch?v=OYYRHIKBMAo',280,7,1908),
	 ('Deathwish','Three Days Grace','Alienation','https://www.youtube.com/watch?v=wcX70UjeejA',193,2,188),
	 ('DEGENERATE','STARSET','SILOS','https://www.youtube.com/watch?v=Fzq8OcWTFYk',216,10,2107),
	 ('DEVOLUTION','STARSET','HORIZONS','https://www.youtube.com/watch?v=f6rMASco-2g',309,3,768),
	 ('DIE FOR YOU','STARSET','Vessels','https://www.youtube.com/watch?v=bntcMIMPS5k',317,1,308),
	 ('Die For You (Acoustic Version)','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=cAhX8xiS7pw',270,2,525),
	 ('DIVING BELL','STARSET','DIVISIONS','https://www.youtube.com/watch?v=NOPoqtRSQs8',338,21,6291);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Divisive','Disturbed','Divisive','https://www.youtube.com/watch?v=yECMX9QfKtE',238,0,0),
	 ('Dominate','Three Days Grace','Alienation','https://www.youtube.com/watch?v=szuKMQcNYqI',194,1,189),
	 ('Don''t Stay','Linkin Park','Meteora','https://www.youtube.com/watch?v=O1WAuqn9t0o',187,1,183),
	 ('Don''t Tell Me (feat. Ann Wilson)','Disturbed, Ann Wilson','Divisive','https://www.youtube.com/watch?v=3xpv_MIfucg',271,1,265),
	 ('Don''t Wanna Go Home Tonight','Three Days Grace','Alienation','https://www.youtube.com/watch?v=f78mwD8_N_o',211,1,3),
	 ('Down With The Fallen','STARSET','Transmissions','https://www.youtube.com/watch?v=DuoUcz7XqjA',257,2,250),
	 ('DREAMCATCHER','STARSET','HORIZONS','https://www.youtube.com/watch?v=-WAqLcLB8vk',293,1,288),
	 ('Droppin'' Plates','Disturbed','The Sickness','https://www.youtube.com/watch?v=oHFru-YAMTs',228,1,128),
	 ('DYSTOPIA','STARSET','SILOS','https://www.youtube.com/watch?v=lgTG5hj5fxQ',277,8,2157),
	 ('EARTHRISE','STARSET','HORIZONS','https://www.youtube.com/watch?v=Cm3Pi0u7XOQ',296,4,720);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('ECHO','STARSET','DIVISIONS','https://www.youtube.com/watch?v=c87I0v6PNW0',216,19,4161),
	 ('Everglow','STARSET','Vessels','https://www.youtube.com/watch?v=hwJJMfVHCaA',476,4,632),
	 ('Expectations','Three Days Grace','Transit Of Venus','https://www.youtube.com/watch?v=Oh92mave0M0',163,1,162),
	 ('Façade','Disturbed','Indestructible','https://www.youtube.com/watch?v=vUdaBnfEmvE',225,1,219),
	 ('Faint','Linkin Park','Meteora','https://www.youtube.com/watch?v=yOW7Eh81Gto',162,1,158),
	 ('FAULTLINE','STARSET','DIVISIONS','https://www.youtube.com/watch?v=il8GouWoG-M',216,20,3643),
	 ('Feeding the Fire','Disturbed','Divisive','https://www.youtube.com/watch?v=bUETwXynXUU',259,1,252),
	 ('Figure.09','Linkin Park','Meteora','https://www.youtube.com/watch?v=rKdgl8OUKpk',197,1,192),
	 ('Fire It Up','Disturbed','Immortalized','https://www.youtube.com/watch?v=XgNqAMCZAFQ',245,2,239),
	 ('First Light','STARSET','Transmissions','https://www.youtube.com/watch?v=VW3Zn4c9pVY',84,3,246);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Foreword','Linkin Park','Meteora','https://www.youtube.com/watch?v=Ccvqxa8vMGQ',13,2,4),
	 ('Forgiven','Disturbed','Ten Thousand Fists','https://www.youtube.com/watch?v=n5C58nZVyrY',252,1,246),
	 ('Forgotten','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=9AB6Vo739UU',194,3,756),
	 ('Frequency','STARSET','Vessels','https://www.youtube.com/watch?v=9Vd9ZaHy7jM',281,4,1099),
	 ('Get A Life','Limp Bizkit','Gold Cobra','https://www.youtube.com/watch?v=ukTdSKBlBkw',294,1,290),
	 ('Golden Sign _m','Sān-Z, HOYO-MiX, Mr.mo','极限委托','https://www.youtube.com/watch?v=BcWsI_d0RP0',68,1,66),
	 ('Gone Forever','Three Days Grace','One-X','https://www.youtube.com/watch?v=GbfOBGhRbe0',221,1,0),
	 ('Gravity Of You','STARSET','Vessels','https://www.youtube.com/watch?v=wkdg-0vN6xw',286,3,753),
	 ('H.I.A.的未来','Sān-Z, HOYO-MiX','极限委托','https://www.youtube.com/watch?v=RsDDY7mrkHU',17,1,0),
	 ('Halo (Acoustic)','STARSET','Transmissions','https://www.youtube.com/watch?v=1jwdXSDRstE',216,1,210);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('HEAD OVER HEELS','STARSET','SILOS','https://www.youtube.com/watch?v=70g0tfLRrfw',298,9,2340),
	 ('Hia','Sān-Z, HOYO-MiX','极限委托','https://www.youtube.com/watch?v=TDHcWpdEhTE',106,1,0),
	 ('Hit the Floor','Linkin Park','Meteora','https://www.youtube.com/watch?v=Ablk0NUR1kU',164,11,1927),
	 ('Home','Three Days Grace','Three Days Grace','https://www.youtube.com/watch?v=6Xu_FG23xXY',260,1,256),
	 ('I Hate Everything About You','Three Days Grace','Three Days Grace','https://www.youtube.com/watch?v=prZrgyueXwE',231,1,2),
	 ('ICARUS','STARSET','HORIZONS','https://www.youtube.com/watch?v=lV04KP1jY0M',289,2,565),
	 ('Immortalized','Disturbed','Immortalized','https://www.youtube.com/watch?v=pwoVqxn82AA',257,1,0),
	 ('In the End','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=KFA1hM91ffo',216,3,425),
	 ('INFECTED','STARSET','HORIZONS','https://www.youtube.com/watch?v=iImwzIiL33Q',188,2,183),
	 ('It Has Begun','STARSET','Transmissions','https://www.youtube.com/watch?v=JmFVg84TbdI',316,2,617);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Just Like You','Three Days Grace','Three Days Grace','https://www.youtube.com/watch?v=zMQh3obrz5k',186,1,4),
	 ('Land of Confusion','Disturbed','Ten Thousand Fists','https://www.youtube.com/watch?v=3wtqy_dKDVM',287,2,102),
	 ('Landmine','Three Days Grace','Human','https://www.youtube.com/watch?v=vFA-ofa927w',205,1,200),
	 ('Last To Fall','STARSET','Vessels','https://www.youtube.com/watch?v=aCvqSp_K5IE',303,2,589),
	 ('LEAVING THIS WORLD BEHIND','STARSET','HORIZONS','https://www.youtube.com/watch?v=hUnwQjO63Ws',267,3,520),
	 ('Let It Die','Three Days Grace','One-X','https://www.youtube.com/watch?v=7Zm3ZIsFZkg',189,4,980),
	 ('Let It Die (Acoustic)','STARSET','Transmissions','https://www.youtube.com/watch?v=qgrYNroBbak',195,2,381),
	 ('Let It Die (Maniac Agenda Remix)','STARSET','Transmissions','https://www.youtube.com/watch?v=jjD42meeoNU',452,5,880),
	 ('Let You Down','Three Days Grace','Three Days Grace','https://www.youtube.com/watch?v=7DTjkztPQPg',224,1,6),
	 ('Limbo','Sān-Z, HOYO-MiX','极限委托','https://www.youtube.com/watch?v=0p30IRLBEnc',129,1,0);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Lost in You','Three Days Grace','Life Starts Now','https://www.youtube.com/watch?v=yaYJ68Akj2M',232,1,27),
	 ('Love You To Death','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=61PvDYeudT4',332,2,0),
	 ('Lying from You','Linkin Park','Meteora','https://www.youtube.com/watch?v=zbUcO3J3UYE',175,2,170),
	 ('MANIFEST','STARSET','DIVISIONS','https://www.youtube.com/watch?v=jPofvnz5lDI',267,28,7801),
	 ('Me Against You','Three Days Grace','Outsider','https://www.youtube.com/watch?v=R7yA6VA5D8w',209,1,50),
	 ('Mind Of Les','Limp Bizkit','Significant Other','https://www.youtube.com/watch?v=0N_k4ZU7jOw',101,1,52),
	 ('Monster','STARSET','Vessels','https://www.youtube.com/watch?v=dPqixofTN98',256,1,249),
	 ('My Demons','STARSET','Transmissions','https://www.youtube.com/watch?v=Or9FqF0qZBs',288,1,280),
	 ('My Demons (Acoustic)','STARSET','Transmissions','https://www.youtube.com/watch?v=DHnH3LdfLok',214,3,375),
	 ('My Demons (Synchronice Remix)','STARSET','Transmissions','https://www.youtube.com/watch?v=nSHsVLKW-lc',233,2,457);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Never Again','Disturbed','Asylum','https://www.youtube.com/watch?v=PdAxPnmANjo',213,1,0),
	 ('Never Too Late','Three Days Grace','One-X','https://www.youtube.com/watch?v=SRbA_JzFKuA',209,1,0),
	 ('Never Wrong','Disturbed','Immortalized','https://www.youtube.com/watch?v=K3iSODuxPWE',213,2,415),
	 ('New Divide','Linkin Park','Papercuts','https://www.youtube.com/watch?v=t19wM1gn1Wo',269,1,262),
	 ('No More','Three Days Grace','Life Starts Now','https://www.youtube.com/watch?v=QK6rJ_fcEPM',225,1,219),
	 ('Nobody''s Listening','Linkin Park','Meteora','https://www.youtube.com/watch?v=ek3TR-g2at0',178,1,125),
	 ('Nothing To Lose But You','Three Days Grace','Outsider','https://www.youtube.com/watch?v=URRPGpxsGOg',172,1,0),
	 ('Nothing''s Fair In Love and War','Three Days Grace','Human','https://www.youtube.com/watch?v=syIEyErlNzM',224,2,224),
	 ('Numb','Linkin Park','Meteora','https://www.youtube.com/watch?v=u-IcadiJCrE',187,11,2006),
	 ('Numb / Encore','Jay-Z, Linkin Park','Papercuts','https://www.youtube.com/watch?v=w236Se63-_A',206,1,201);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('One Step Closer','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=KwN_f0fTHoE',157,3,537),
	 ('Open Your Eyes','Disturbed','Immortalized','https://www.youtube.com/watch?v=mg5UEWBfOHM',237,1,231),
	 ('Original Me (1St Take Ver.)','Sān-Z, HOYO-MiX','Stars of Lyra+','https://www.youtube.com/watch?v=sHvacnqgeFg',223,1,0),
	 ('Original Me (Instrumental)','Sān-Z, HOYO-MiX','Stars of Lyra+','https://www.youtube.com/watch?v=HQ4l-caJjnY',223,1,30),
	 ('OTHER WORLDS THAN THESE','STARSET','DIVISIONS','https://www.youtube.com/watch?v=jiXLe2TgR20',258,22,5529),
	 ('OTHERWORLDLY','STARSET','HORIZONS','https://www.youtube.com/watch?v=QjZP-YpvfpI',302,3,831),
	 ('Overrated','Three Days Grace','Three Days Grace','https://www.youtube.com/watch?v=9qI943oi6mU',210,1,205),
	 ('Papercut','Linkin Park','Papercuts','https://www.youtube.com/watch?v=2K-evRnwcSc',186,2,401),
	 ('Perfect Insanity','Disturbed','Indestructible','https://www.youtube.com/watch?v=q0jCq6wwoEk',236,1,9),
	 ('PERFECT MACHINE','STARSET','DIVISIONS','https://www.youtube.com/watch?v=XM9H2IQVG2U',323,22,6922);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('pinKing','HOYO-MiX, Sān-Z','pinKing','https://www.youtube.com/watch?v=DugA46SEuPc',187,1,23),
	 ('Point Of No Return','STARSET','Transmissions','https://www.youtube.com/watch?v=0de-SmoVpiE',219,1,214),
	 ('Point Of No Return (Acoustic)','STARSET','Transmissions','https://www.youtube.com/watch?v=cfynGkvxEY0',236,3,691),
	 ('Points of Authority','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=UtSsEfJerRg',200,1,196),
	 ('praesens','STARSET','SILOS','https://www.youtube.com/watch?v=EpPrcETCfX4',121,9,591),
	 ('Prayer','Disturbed','Believe','https://www.youtube.com/watch?v=cIAp-ehzmxI',219,1,214),
	 ('Pushing Me Away','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=QyWR34MpMiE',191,1,372),
	 ('Remember','Disturbed','Believe','https://www.youtube.com/watch?v=NOtZguxf0uo',248,1,241),
	 ('requiem of the order','STARSET','SILOS','https://www.youtube.com/watch?v=fmp4P6qEBkQ',236,7,1607),
	 ('Ricochet','STARSET','Vessels','https://www.youtube.com/watch?v=AmqcKbBpI6Y',310,3,612);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('Ricochet (Acoustic Version)','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=t3io6hf7fL8',292,1,285),
	 ('rise of messenger','STARSET','SILOS','https://www.youtube.com/watch?v=wIzghSAG75E',134,9,1173),
	 ('Runaway','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=xMyS6c2PeXU',184,4,562),
	 ('Satellite','STARSET','Vessels','https://www.youtube.com/watch?v=LyJAoB_OmdE',239,4,759),
	 ('Satellite (Acoustic Version)','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=bafXX8J5sng',230,2,450),
	 ('Save Our Last Goodbye','Disturbed','Immortalized','https://www.youtube.com/watch?v=8p8NKNNyQ8w',299,1,292),
	 ('Serpentine','Disturbed','Asylum','https://www.youtube.com/watch?v=y9kBre_1TEo',249,1,243),
	 ('Session','Linkin Park','Meteora','https://www.youtube.com/watch?v=rL_q2fBNSnQ',144,2,141),
	 ('SHATTERED DREAMS','STARSET','SILOS','https://www.youtube.com/watch?v=S2B0qJfKvB8',249,9,1796),
	 ('SILOS','STARSET','SILOS','https://www.youtube.com/watch?v=DPbtkj1wbVE',261,9,2034);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('So What','Three Days Grace','Human','https://www.youtube.com/watch?v=mtkba-c2Ors',177,1,174),
	 ('SOLSTICE','STARSET','DIVISIONS','https://www.youtube.com/watch?v=Dt25fEpLseM',341,20,6318),
	 ('SOMETHING WICKED','STARSET','HORIZONS','https://www.youtube.com/watch?v=ZntiHhT-izQ',239,2,466),
	 ('Starlight','STARSET','Vessels','https://www.youtube.com/watch?v=vLhwFOkfZOg',286,2,558),
	 ('Starlight (Acoustic Version)','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=ek93gmwTB2A',287,2,561),
	 ('Stars Align (feat. Astra Yao)','Sān-Z, HOYO-MiX, Astra Yao','Stars Align (feat. Astra Yao)','https://www.youtube.com/watch?v=UGfUaFjNNL4',230,1,104),
	 ('Stay Too Long (Pendulum Remix)','Plan B','Stay Too Long','https://www.youtube.com/watch?v=gxoVRqVDpwE',426,1,825),
	 ('STRATOSPHERE','STARSET','DIVISIONS','https://www.youtube.com/watch?v=-vH1S16mLrA',257,23,5341),
	 ('SWAY','STARSET','SILOS','https://www.youtube.com/watch?v=n5ox5h5lBOY',257,8,2006),
	 ('SYMBIOTIC','STARSET','HORIZONS','https://www.youtube.com/watch?v=7C2WlRJ-L5k',203,2,396);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('TELEKINETIC','STARSET','DIVISIONS','https://www.youtube.com/watch?v=R_2wN_Fs794',312,18,5733),
	 ('Telepathic','STARSET','Vessels','https://www.youtube.com/watch?v=5RSgSx6KE6c',282,1,278),
	 ('Telepathic (Acoustic Version)','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=3CJzN8L1TyQ',231,2,449),
	 ('Telepathic (Not Your Dope Remix)','STARSET','Vessels 2.0','https://www.youtube.com/watch?v=a4FoIv-WF6U',217,2,426),
	 ('Telescope','STARSET','Transmissions','https://www.youtube.com/watch?v=saHTi6LTcGU',331,3,965),
	 ('Telescope (EmoTek Remix)','STARSET','Transmissions','https://www.youtube.com/watch?v=mxWvaw5k7rQ',420,3,408),
	 ('temple of milton','STARSET','SILOS','https://www.youtube.com/watch?v=TBniFYBOPZM',127,9,1239),
	 ('the antihero''s journey','STARSET','SILOS','https://www.youtube.com/watch?v=QWnpG1hKUCI',104,8,712),
	 ('The Best Ones Lie','Disturbed','Evolution','https://www.youtube.com/watch?v=kv6ev6zsukc',242,1,35),
	 ('THE BREACH','STARSET','HORIZONS','https://www.youtube.com/watch?v=3xhpkdf0Vqk',260,2,505);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('The Future Is Now','STARSET','Transmissions','https://www.youtube.com/watch?v=dT_boUyq4UM',285,2,556),
	 ('The Light','Disturbed','Immortalized','https://www.youtube.com/watch?v=buaJabSblAU',256,1,250),
	 ('The Mountain','Three Days Grace','Outsider','https://www.youtube.com/watch?v=z6rPrN_ac5U',198,1,194),
	 ('The Order','STARSET','Vessels','https://www.youtube.com/watch?v=MlE1srK-Pp0',67,1,66),
	 ('The Power','Three Days Grace','Alienation','https://www.youtube.com/watch?v=Kucd-Lbhw84',217,2,225),
	 ('The Sound of Silence','Disturbed','Immortalized','https://www.youtube.com/watch?v=xrg3XFwW6v4',248,1,242),
	 ('The Vengeful One','Disturbed','Immortalized','https://www.youtube.com/watch?v=tS-J1TLsFxs',252,2,0),
	 ('THIS ENDLESS ENDEAVOR','STARSET','HORIZONS','https://www.youtube.com/watch?v=-THcFQaDPF0',302,1,294),
	 ('Time of Dying','Three Days Grace','One-X','https://www.youtube.com/watch?v=05wXNKzOkRM',186,1,173),
	 ('Time That Remains','Three Days Grace','Transit Of Venus','https://www.youtube.com/watch?v=tzxmgsikA-Y',192,1,74);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('title','artist','album','comment',0,9,1201),
	 ('TOKSIK','STARSET','SILOS','https://www.youtube.com/watch?v=TE7DN0kGl7U',231,9,1818),
	 ('TRIALS','STARSET','DIVISIONS','https://www.youtube.com/watch?v=Wfs-pP0dQ3c',258,19,4405),
	 ('Unbecoming','STARSET','Vessels','https://www.youtube.com/watch?v=H23tJk5zGG0',250,2,488),
	 ('UNVEILING THE ARCHITECTURE','STARSET','HORIZONS','https://www.youtube.com/watch?v=pIRAelRsOq0',105,3,0),
	 ('Villain I''m Not','Three Days Grace','Outsider','https://www.youtube.com/watch?v=W21-14Od2Nk',175,1,118),
	 ('WAKING UP','STARSET','DIVISIONS','https://www.youtube.com/watch?v=BCwAAI3QaIY',229,20,3807),
	 ('Want','Disturbed','The Sickness','https://www.youtube.com/watch?v=PdhISJNYC5k',232,1,227),
	 ('What Are You Waiting For','Disturbed','Immortalized','https://www.youtube.com/watch?v=JoUqSdRSjBI',243,2,714),
	 ('What I''ve Done','Linkin Park','Papercuts','https://www.youtube.com/watch?v=IgCHFfDFivc',207,1,200);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('WHERE THE SKIES END','STARSET','DIVISIONS','https://www.youtube.com/watch?v=jocoQvSdy84',393,27,9414),
	 ('Who','Disturbed','Immortalized','https://www.youtube.com/watch?v=57LPNpIIwmc',286,1,279),
	 ('With You','Linkin Park','Hybrid Theory','https://www.youtube.com/watch?v=r_STxOOnQGg',203,3,598),
	 ('Without You','Three Days Grace','Life Starts Now','https://www.youtube.com/watch?v=5R39U-4GrRE',213,1,209),
	 ('世界全剧终，欢迎来到新艾利都！','Sān-Z, HOYO-MiX','极限委托：PV原声集 (游戏《绝区零》原声集)','https://www.youtube.com/watch?v=c5jW5vhFPhg',156,1,152),
	 ('卡吕冬的骑行','Sān-Z, HOYO-MiX, Ai Mori','极限委托：PV原声集 (游戏《绝区零》原声集)','https://www.youtube.com/watch?v=oA1u7OApDN4',134,2,120),
	 ('奇迹的起点','Sān-Z, HOYO-MiX','极限委托：PV原声集 (游戏《绝区零》原声集)','https://www.youtube.com/watch?v=Y1C3owRf8CY',238,1,232),
	 ('成就达成率......100%','Sān-Z, HOYO-MiX, 三畿道','极限委托：PV原声集 (游戏《绝区零》原声集)','https://www.youtube.com/watch?v=jfS1bQ66Yuw',92,2,24),
	 ('无尽的施工日','白昼, Sān-Z, HOYO-MiX, Mr.mo','极限委托','https://www.youtube.com/watch?v=4-uK65NNWMU',242,1,238),
	 ('絵本','Sān-Z, HOYO-MiX','絵本','https://www.youtube.com/watch?v=tHvqR5mb5Vg',154,1,104);
INSERT INTO musicindex.musicspy (title,artist,album,url,`length`,timesSeen,playtime) VALUES
	 ('致命审讯','Sān-Z, HOYO-MiX, 狐妖Mikan','极限委托：PV原声集 (游戏《绝区零》原声集)','https://www.youtube.com/watch?v=9X8QNxRD91M',134,1,0),
	 ('降噪测试','Sān-Z, HOYO-MiX','极限委托：PV原声集 (游戏《绝区零》原声集)','https://www.youtube.com/watch?v=0OhvnUkUFho',150,1,28);
